version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "tu-usuario-github"
    assignees:
      - "tu-usuario-github"
    commit-message:
      prefix: "npm"
      include: "scope"