name: Qodana

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - ftr-newApiConfigUpdate
      - ftr_arreglo_errores
      - 'releases/**'   # patrón para subramas
      - 'hotfix/**'
  pull_request:
    branches:
      - main
      - dev
      - 'releases/**'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      # Para pushes y dispatch: checkout normal
      - name: Checkout (push/dispatch)
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Para PRs: checkout del commit HEAD del PR (no el merge commit)
      - name: Checkout PR HEAD
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2025.1
        with:
          pr-mode: false   
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          QODANA_ENDPOINT: https://qodana.cloud
